// Generated by https://quicktype.io

export interface Article {
  object: string;
  id: string;
  created_time: string;
  last_edited_time: string;
  created_by: CreatedBy;
  last_edited_by: CreatedBy;
  has_children: boolean;
  archived: boolean;
  type: string;
  child_page: ChildPage;
}

export interface ChildPage {
  title: string;
}

export interface CreatedBy {
  object: string;
  id: string;
}
